# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zHb-AVCyHBRNHUq9wZKLbi_k-csC_Dl-
"""

import gradio as gr
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

# load model
model = load_model("scene_model.h5", compile=False)

# class labels
class_names = ['buildings', 'forest', 'glacier', 'mountain', 'sea', 'street']

# prediction function
def predict(img):
    img = img.resize((100,100))
    img_array = np.array(img)/255.0
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array)
    return class_names[np.argmax(prediction)]

# interface
demo = gr.Interface(
    fn=predict,
    inputs=gr.Image(type="pil"),
    outputs="text",
    title="Natural Scene Classification"
)

demo.launch()